### ISSUE TITLE
why c- before classnames?

### ISSUE THREAD

**Issue by vre2h** [sabovyan/nike-history#1]
https://github.com/sabovyan/nike-history/blob/8f30c2730d6aed4caaa141ad24130d94a9f55eaa/src/survey.html#L63

**Comment by sabovyan** [comment]
"c" stands for a component. I have seen this kind of naming convention from the "More Transparent UI Code with Namespaces" article (link - https://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/ ). I found it quite useful. It helps to increase the readability of the code.
